version: 2
sources:
  - name: postgres
    database: banco_dremio_sql # Certifique-se de que corresponde ao nome do seu banco de dados
    schema: public # Certifique-se de que corresponde ao esquema correto
    tables:
      - name: tb_cliente
      - name: tb_venda